using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.Json;

namespace Arke.ARI.SourceGenerator
{
    /// <summary>
    /// Main source generator that replaces T4 templates
    /// </summary>
    [Generator]
    public class ARISourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            // No initialization needed for this generator
        }

        public void Execute(GeneratorExecutionContext context)
        {
            try
            {
                // Load embedded JSON schemas
                var schemas = LoadEmbeddedSchemas();

                // Create generators
                var generators = new List<ICodeGenerator>
                {
                    new ModelGenerator(),
                    new ActionInterfaceGenerator(), 
                    new ActionClassGenerator(),
                    new EventGenerator(),
                    new ClientGenerator()
                };

                // Generate code for each schema
                foreach (var schema in schemas)
                {
                    foreach (var generator in generators)
                    {
                        var generatedCode = generator.Generate(schema.Value);
                        if (!string.IsNullOrEmpty(generatedCode.Code))
                        {
                            context.AddSource(generatedCode.FileName, SourceText.From(generatedCode.Code, Encoding.UTF8));
                        }
                    }
                }

                // Generate the main client file
                GenerateMainClient(context, schemas);
            }
            catch (Exception ex)
            {
                // Report diagnostics for any errors
                var descriptor = new DiagnosticDescriptor(
                    "ARI001",
                    "Source generation error",
                    "An error occurred during source generation: {0}",
                    "Arke.ARI.SourceGenerator",
                    DiagnosticSeverity.Error,
                    true
                );

                context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, ex.Message));
            }
        }

        private Dictionary<string, ApiSchema> LoadEmbeddedSchemas()
        {
            var assembly = typeof(ARISourceGenerator).Assembly;
            var schemas = new Dictionary<string, ApiSchema>();

            var resourceNames = new[]
            {
                "Applications.json", "Asterisk.json", "Bridges.json", 
                "Channels.json", "DeviceStates.json", "Endpoints.json",
                "Events.json", "Mailboxes.json", "Playbacks.json",
                "Recordings.json", "Sounds.json"
            };

            foreach (var resourceName in resourceNames)
            {
                var fullResourceName = $"Arke.ARI.SourceGenerator.Resources.{resourceName}";
                using var stream = assembly.GetManifestResourceStream(fullResourceName);
                
                if (stream != null)
                {
                    using var reader = new StreamReader(stream);
                    var json = reader.ReadToEnd();
                    var schema = JsonSerializer.Deserialize<ApiSchema>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                    
                    var key = Path.GetFileNameWithoutExtension(resourceName);
                    schemas[key] = schema;
                }
            }

            return schemas;
        }

        private void GenerateMainClient(GeneratorExecutionContext context, Dictionary<string, ApiSchema> schemas)
        {
            // This would generate the main ARIClient.cs file
            // Implementation would collect all events from schemas and generate the client
            var code = GenerateARIClientCode(schemas);
            context.AddSource("Generated.ARIClient.cs", SourceText.From(code, Encoding.UTF8));
        }

        private string GenerateARIClientCode(Dictionary<string, ApiSchema> schemas)
        {
            var code = new StringBuilder();
            
            code.AppendLine("/*");
            code.AppendLine("   Arke ARI Framework");
            code.AppendLine($"   Automatically generated file @ {DateTime.Now}");
            code.AppendLine("   Generated by Roslyn Source Generator");
            code.AppendLine("*/");
            code.AppendLine("using System;");
            code.AppendLine("using System.Collections.Generic;");
            code.AppendLine("using Arke.ARI.Models;");
            code.AppendLine();
            code.AppendLine("namespace Arke.ARI");
            code.AppendLine("{");
            
            // Generate event delegates
            var events = CollectEventTypes(schemas);
            foreach (var eventType in events)
            {
                code.AppendLine($"    public delegate void {eventType}Handler(IAriClient sender, {eventType} e);");
            }
            
            code.AppendLine("    public delegate void UnhandledEventHandler(object sender, Arke.ARI.Models.Event eventMessage);");
            code.AppendLine();
            
            // Generate interface
            code.AppendLine("    public interface IAriEventClient");
            code.AppendLine("    {");
            foreach (var eventType in events)
            {
                code.AppendLine($"        event {eventType}Handler On{eventType};");
            }
            code.AppendLine("        event UnhandledEventHandler OnUnhandledEvent;");
            code.AppendLine("    }");
            code.AppendLine();
            
            // Generate base client
            code.AppendLine("    public class BaseAriClient : IAriEventClient");
            code.AppendLine("    {");
            code.AppendLine("        // Event declarations and implementation would go here");
            code.AppendLine("        // This is a simplified example");
            code.AppendLine("    }");
            code.AppendLine("}");
            
            return code.ToString();
        }

        private List<string> CollectEventTypes(Dictionary<string, ApiSchema> schemas)
        {
            var events = new List<string>();
            
            // This would analyze schemas to find event types
            // Simplified for example
            events.Add("ApplicationReplacedEvent");
            events.Add("BridgeCreatedEvent");
            events.Add("ChannelCreatedEvent");
            
            return events;
        }
    }

    /// <summary>
    /// Interface for code generators
    /// </summary>
    public interface ICodeGenerator
    {
        GeneratedCode Generate(ApiSchema schema);
    }

    /// <summary>
    /// Represents generated source code
    /// </summary>
    public class GeneratedCode
    {
        public string FileName { get; }
        public string Code { get; }

        public GeneratedCode(string fileName, string code)
        {
            FileName = fileName;
            Code = code;
        }
    }

    /// <summary>
    /// Placeholder implementations for demonstration
    /// </summary>
    public class ModelGenerator : ICodeGenerator
    {
        public GeneratedCode Generate(ApiSchema schema)
        {
            // Implementation would generate model classes
            return new GeneratedCode($"Generated.Models.{schema.GetType().Name}.cs", "// Model classes would be generated here");
        }
    }

    public class ActionInterfaceGenerator : ICodeGenerator
    {
        public GeneratedCode Generate(ApiSchema schema)
        {
            // Implementation would generate action interfaces
            return new GeneratedCode($"Generated.Interfaces.{schema.GetType().Name}.cs", "// Action interfaces would be generated here");
        }
    }

    public class ActionClassGenerator : ICodeGenerator
    {
        public GeneratedCode Generate(ApiSchema schema)
        {
            // Implementation would generate action classes
            return new GeneratedCode($"Generated.Actions.{schema.GetType().Name}.cs", "// Action classes would be generated here");
        }
    }

    public class EventGenerator : ICodeGenerator
    {
        public GeneratedCode Generate(ApiSchema schema)
        {
            // Implementation would generate event classes
            return new GeneratedCode($"Generated.Events.{schema.GetType().Name}.cs", "// Event classes would be generated here");
        }
    }

    public class ClientGenerator : ICodeGenerator
    {
        public GeneratedCode Generate(ApiSchema schema)
        {
            // Implementation would contribute to client generation
            return new GeneratedCode("", ""); // Client is generated separately
        }
    }

    /// <summary>
    /// Schema models for JSON deserialization
    /// </summary>
    public class ApiSchema
    {
        public string ApiVersion { get; set; }
        public string SwaggerVersion { get; set; }
        public string BasePath { get; set; }
        public string ResourcePath { get; set; }
        public List<ApiEndpoint> Apis { get; set; } = new();
        public Dictionary<string, ModelDefinition> Models { get; set; } = new();
    }

    public class ApiEndpoint
    {
        public string Path { get; set; }
        public string Description { get; set; }
        public List<Operation> Operations { get; set; } = new();
    }

    public class Operation
    {
        public string HttpMethod { get; set; }
        public string Summary { get; set; }
        public string Notes { get; set; }
        public string Nickname { get; set; }
        public string ResponseClass { get; set; }
        public List<Parameter> Parameters { get; set; } = new();
        public List<ErrorResponse> ErrorResponses { get; set; } = new();
    }

    public class Parameter
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ParamType { get; set; }
        public bool Required { get; set; }
        public string DataType { get; set; }
    }

    public class ErrorResponse
    {
        public int Code { get; set; }
        public string Reason { get; set; }
    }

    public class ModelDefinition
    {
        public string Id { get; set; }
        public string Description { get; set; }
        public Dictionary<string, PropertyDefinition> Properties { get; set; } = new();
        public List<string> SubTypes { get; set; } = new();
    }

    public class PropertyDefinition
    {
        public string Type { get; set; }
        public string Description { get; set; }
        public bool Required { get; set; }
    }
}